name: Docker Build and Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.1.5

      - name: Create cache directories
        run: mkdir -p ~/.cache/deno && mkdir -p ~/.deno
        
      - name: Cache Deno dependencies
        uses: actions/cache@v4
        with:
            path: |
              ~/.cache/deno
              ~/.deno
            key: ${{ runner.os }}-deno-v1-${{ hashFiles('deno.lock') }}
            restore-keys: |
              ${{ runner.os }}-deno-
              
      - name: Install Deno Task
        run: deno install --allow-scripts=npm:@carbon/grid@11.30.0,npm:@carbon/layout@11.28.0

      - name: Download dependencies
        run: deno cache backend/main.ts
            
      - name: Build
        run: deno task build

      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: latest ${{ github.sha }}
          containerfiles: |
            ./infra/docker/Dockerfile
          context: .

      - name: Push To Registry
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
